version: '3.9'

services:
  web:
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000 # new
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=QnyGkISOunhhNUks3QdXsLjT_Rxv8uFAblid4pgInk0JdoQ2ZFc"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False" # new
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: